language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
    secure: LE0ESSk4xUUZUJafYGYm2jT+OEoXZciqZmLNmSHyx6l0SSMn/gwIayz3YLQ05MBg4X74m6FOU8niTa8b3KhGDk/jOXAU2tkGtfUsbxPqjK/DwH7nY5+kWGHFkmJgltjXAyIZUCYYbIeEmpCV0HEHEHjoIHxmrgL2lHGfhEiyhvg=
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
